version: '3.5'

volumes: 
  user-db-data:

networks: 
  esbay-network:
    driver: bridge

services:
  user:
    build:
      context: ./user-ms
    ports:
      - 8082:5000
    depends_on: 
      - user_db
    restart: always
    networks: 
      - esbay-network
  
  user_db:
    image: mysql:5.7.22
    volumes: 
      - user-db-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_DATABASE=user
    restart: always
    networks:
      - esbay-network